apiVersion: v1
kind: Secret
metadata:
  name: calorieasy-secrets
  labels:
    {{- include "calorieasy.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_JWT_SECRET: {{ .Values.jwt.secret | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
  OPENAI_API_KEY: {{ .Values.genai.openaiApiKey | quote }}
  TEXT_OPENAI_API_KEY: {{ .Values.genai.textOpenaiApiKey | quote }}
  USDA_FDC_API_KEY: {{ .Values.genai.usdaApiKey | quote }}
